### PR TITLE
CREATE_TRIGGER support

### LINKED ISSUE #8: Incorrectly splitting CREATE TRIGGER queries (sqlite3)
The following is a single query for sqlite3:

```sql
CREATE TRIGGER sqlmods
         AFTER UPDATE
            ON bar
      FOR EACH ROW
          WHEN old.yay IS NULL
BEGIN
    UPDATE bar
       SET yay = 1
     WHERE rowid = NEW.rowid;
END;
```
The library identifies two queries, but it should identify one. The first `;` should be ignored.

### PR DESCRIPTION
**Pull request by rathboma**
- Ignore semi-colons until after `END`
- I have no idea if this is the best way to do it, but it works

Questions:
- I've added a `dialect` option to support the weird SQLITE CREATE TRIGGER syntax. That cool?

Fixes #8 

@maxcnunes if you have some time I would appreciate your input.

### CODE REVIEW

File: src/parser.js [hunk 1]
```diff
@@ -380,7 +394,17 @@ function stateMachineStatementParser (isStrict, statement, steps) {
...
 
       if (token.type === 'semicolon') {
-        statement.endStatement = ';';
+        // sqlite triggers have different syntax
+        if (dialect === 'sqlite' && (statement.type === 'CREATE_TRIGGER' && !statement.canEnd)) {
+          // do nothing
+        } else {
+          statement.endStatement = ';';
+          return;
+        }
```
Comment (MasterOdin) [inline src/parser.js:403]: I think we can skip the empty if clause, and perhaps expand the above comment to include what about sqlite triggers is different (e.g. they include a semi-colon inside of their execute statement)

```suggestion
        if (dialect !== 'sqlite' || statement.type !== 'CREATE_TRIGGER' || statement.canEnd) {
          statement.endStatement = ';';
          return;
        }
```

File: test/identifier/single-statement.spec.js [hunk 2]
```diff
@@ -36,6 +36,34 @@ describe('identifier', function () {
...
+        {
+          start: 0,
+          end: 104,
+          text: 'CREATE TRIGGER view_insert INSTEAD OF INSERT ON my_view FOR EACH ROW EXECUTE PROCEDURE view_insert_row();',
+          type: 'CREATE_TRIGGER',
+          executionType: 'MODIFICATION',
+        },
+      ];
+      expect(actual).to.eql(expected);
+    });
```
Comment (MasterOdin) [inline test/identifier/single-statement.spec.js:65]: should add a test case for [sqlserver](https://docs.microsoft.com/en-us/sql/t-sql/statements/create-trigger-transact-sql?view=sql-server-ver15) as it can also include non-ending semi-colons. Here is an example of one from that doc page:

```sql
CREATE TRIGGER Purchasing.LowCredit ON Purchasing.PurchaseOrderHeader  
AFTER INSERT  
AS  
IF (ROWCOUNT_BIG() = 0)
RETURN;
IF EXISTS (SELECT *  
           FROM Purchasing.PurchaseOrderHeader AS p   
           JOIN inserted AS i   
           ON p.PurchaseOrderID = i.PurchaseOrderID   
           JOIN Purchasing.Vendor AS v   
           ON v.BusinessEntityID = p.VendorID  
           WHERE v.CreditRating = 5  
          )  
BEGIN  
RAISERROR ('A vendor''s credit rating is too low to accept new  
purchase orders.', 16, 1);  
ROLLBACK TRANSACTION;  
RETURN   
END;  
```

File: src/parser.js [hunk 3]
```diff
@@ -246,16 +247,29 @@ function createCreateStatementParser (isStrict) {
...
+    //   validation: {
+    //     acceptTokens: [
+    //       { type: 'keyword', value: 'END' },
+    //     ],
+    //     add: (token) => {
+    //       statement.endStatement = 'END'
+    //     }
+    //   },
+    //   postCanGoToNext: () => false,
+    // },
```
Comment (MasterOdin) [inline src/parser.js:269]: Is there a plan to use this commented out code in the future, or is it leftover from earlier efforts to fix this?

**Review by MasterOdin — CHANGES_REQUESTED** [review]

File: src/parser.js [hunk 4]
```diff
@@ -246,16 +247,29 @@ function createCreateStatementParser (isStrict) {
...
   ];
 
-  return stateMachineStatementParser(isStrict, statement, steps);
+  return stateMachineStatementParser(isStrict, statement, steps, dialect);
```
Comment (MasterOdin) [inline src/parser.js:272]: Looking at this PR and the functions in this file, I think we should unify on a consistent ordering of things as we have three different orderings of where `isStrict` and `dialect` go in the function list:

* `parse(query, isStrict, dialect)` (both last, dialect immediately follows isStrict)
* `createStatementParserByToken (isStrict, dialect, token)` (both first, dialect immediately follows isStrict)
* `stateMachineStatementParser(isStrict, statement, steps, dialect)` (isStrict is first, dialect last)

I would advocate for `(isStrict, dialect, ...args)` as this would be the easiest to follow consistently I think with the same two first args in all cases. I do not think we necessarily need to do this refactoring here beyond maybe unifying the arg setup of `createStatementParserByToken` and `stateMachineStatementParser`.

File: src/parser.js (hunk 3 above)
Comment (rathboma) [reply src/parser.js:269]: From earlier efforts. I'll kill this commented code. I was more making this a PR to get some other eyes on it (not to suggest it was final)

File: test/identifier/single-statement.spec.js (hunk 2 above)
Comment (rathboma) [reply test/identifier/single-statement.spec.js:65]: Nice. I'll add this as a test case and include the `END` detection there.

File: src/parser.js (hunk 1 above)
Comment (rathboma) [reply src/parser.js:403]: So I did do it the other way around, but from a code-reading perspective I like the flow of:

```

if <SQLITE>
  // do thing
If <SQLSERVER
  // do thing
```

rather than if not [set of databases]. Feel like it makes it more explicit.

File: src/parser.js (hunk 4 above)
Comment (rathboma) [reply src/parser.js:262]: I actually don't like strict and dialect at the beginning because it makes it hard to extend. What if we added `version` or some other thing in future?

I'd actually prefer `(args, options)`, where options currently includes isStrict and dialect.

I'll do that tidy-up now.

**Comment by rathboma** [comment]
@MasterOdin thoughts?

**Comment by rathboma** [comment]
I'm prepping a Beekeeper Studio release today, if I can get this in there I'd love to. So please let me know if you're cool merging.

**Comment by MasterOdin** [comment]
@rathboma I'll re-review in about an hour when I get home.

**Review by MasterOdin — APPROVED** [review]
